{
 "title": "App Python",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_sum,service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (http_server_duration_milliseconds_count{service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Server Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (http_server_active_requests{service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_duration_milliseconds_sum{service_name=\"$service_name\"} / http_server_duration_milliseconds_count{service_name=\"$service_name\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_server_duration_milliseconds_count{service_name=\"$service_name\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(http_method, service_version, le) (rate(http_server_duration_milliseconds_bucket{service_name=\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_status_code, http_method) (http_server_duration_milliseconds_sum{service_name=\"$service_name\", http_status_code=\"200\"}) / sum by(http_status_code, http_method) (http_server_duration_milliseconds_sum{service_name=\"$service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "616e1d16", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "filters": [
      { "id": "8344b05e", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}